package com.training.backend.config;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.training.backend.entity.*;
import com.training.backend.entity.User.UserRole;
import com.training.backend.repository.*;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

import java.io.InputStream;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * 数据初始化器：管理员/演示学生/竞赛库种子数据
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class DataInitializer implements CommandLineRunner {
    
    private final UserRepository userRepository;
    private final UserProfileRepository profileRepository;
    private final CompetitionRepository competitionRepository;
    private final ForumPostRepository forumPostRepository;
    private final TeamRepository teamRepository;
    private final TeamMemberRepository teamMemberRepository;
    private final ExcellentWorkRepository excellentWorkRepository;
    private final PasswordEncoder passwordEncoder;
    private final ObjectMapper objectMapper;
    private final JdbcTemplate jdbcTemplate;
    
    @Override
    public void run(String... args) {
        migrateNotificationSchema();
        if (userRepository.count() == 0) {
            log.info("初始化演示数据...");
            initUsers();
        }
        if (competitionRepository.count() == 0) {
            initCompetitions();
        } else {
            syncCompetitionData();
        }
        if (forumPostRepository.count() == 0) {
            initForumAndTeams();
        }
        // 每次启动全量同步优秀作品（initExcellentWorks 内部删旧插新）
        initExcellentWorks();
        log.info("数据初始化完成");
    }
    
    /**
     * 迁移:通知表枚举 CHECK 约束(H2)不含新枚举值 ACCEPTED 时,一次性重建该表
     * (Hibernate 的 ddl-auto=update 不会修改旧 CHECK 约束;用 app_migrations 标记避免重复执行)
     */
    private void migrateNotificationSchema() {
        try {
            jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS app_migrations (name VARCHAR(100) PRIMARY KEY)");
            Integer migrated = jdbcTemplate.queryForObject(
                    "SELECT COUNT(*) FROM app_migrations WHERE name = 'notif_enum_v2'", Integer.class);
            if (migrated != null && migrated > 0) {
                return;
            }
            log.warn("执行通知表枚举约束迁移(重建 notifications)");
            jdbcTemplate.execute("DROP TABLE IF EXISTS notifications");
            jdbcTemplate.execute("""
                    CREATE TABLE notifications (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id BIGINT NOT NULL,
                        type VARCHAR(20) NOT NULL,
                        actor_id BIGINT,
                        post_id BIGINT,
                        reply_id BIGINT,
                        summary VARCHAR(120),
                        is_read BOOLEAN NOT NULL,
                        created_at TIMESTAMP
                    )""");
            jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS idx_notif_user ON notifications(user_id)");
            jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS idx_notif_read ON notifications(user_id, is_read)");
            jdbcTemplate.update("INSERT INTO app_migrations(name) VALUES('notif_enum_v2')");
            log.info("notifications 表已重建完成");
        } catch (Exception e) {
            log.warn("通知表迁移检查失败(可忽略): {}", e.getMessage());
        }
    }
    
    /**
     * 已有数据时：按名称同步 competitions.json —— 更新官方链接/富标签等字段，并插入 JSON 中新增的竞赛（upsert）
     */
    private void syncCompetitionData() {
        try {
            ClassPathResource resource = new ClassPathResource("competitions.json");
            if (!resource.exists()) return;
            try (InputStream in = resource.getInputStream()) {
                Map<String, List<Competition>> data = objectMapper.readValue(in, new TypeReference<>() {});
                List<Competition> seed = data.get("competitions");
                if (seed == null) return;
                int updated = 0;
                int inserted = 0;
                for (Competition sc : seed) {
                    var existingOpt = competitionRepository.findByNameContainingIgnoreCase(sc.getName()).stream()
                            .findFirst();
                    if (existingOpt.isPresent()) {
                        Competition existing = existingOpt.get();
                        boolean changed = false;
                        if (sc.getOfficialUrl() != null && !sc.getOfficialUrl().isBlank()
                                && !sc.getOfficialUrl().equals(existing.getOfficialUrl())) {
                            existing.setOfficialUrl(sc.getOfficialUrl());
                            changed = true;
                        }
                        if (sc.getCatalogList() != null && !Objects.equals(sc.getCatalogList(), existing.getCatalogList())) {
                            existing.setCatalogList(sc.getCatalogList());
                            changed = true;
                        }
                        if (sc.getBaoyanBonus() != null && !Objects.equals(sc.getBaoyanBonus(), existing.getBaoyanBonus())) {
                            existing.setBaoyanBonus(sc.getBaoyanBonus());
                            changed = true;
                        }
                        if (sc.getEntryFee() != null && !Objects.equals(sc.getEntryFee(), existing.getEntryFee())) {
                            existing.setEntryFee(sc.getEntryFee());
                            changed = true;
                        }
                        if (sc.getRules() != null && !Objects.equals(sc.getRules(), existing.getRules())) {
                            existing.setRules(sc.getRules());
                            changed = true;
                        }
                        if (changed) {
                            competitionRepository.save(existing);
                            updated++;
                        }
                    } else {
                        competitionRepository.save(sc);
                        inserted++;
                    }
                }
                log.info("竞赛数据同步完成：{} 条种子数据（更新 {}，新增 {}）", seed.size(), updated, inserted);
            }
        } catch (Exception e) {
            log.error("竞赛数据同步失败", e);
        }
    }
    
    private void initUsers() {
        User admin = new User();
        admin.setUsername("admin");
        admin.setPassword(passwordEncoder.encode("admin123"));
        admin.setName("系统管理员");
        admin.setRole(UserRole.ADMIN);
        admin.setEmail("admin@competition-platform.com");
        admin.setDepartment("平台运营");
        userRepository.save(admin);
        
        createDemoStudent("student01", "student123", "张同学", "计算机科学与技术", "工科", 3,
                List.of("编程", "人工智能", "算法"), List.of("Python", "Java"), List.of("保研加分", "能力锻炼"), 8, true);
        createDemoStudent("student02", "student123", "李同学", "金融学", "经管", 2,
                List.of("商业分析", "英语", "写作"), List.of("PPT", "数据分析"), List.of("求职简历"), 5, false);
        createDemoStudent("student03", "student123", "王同学", "数学与应用数学", "理科", 1,
                List.of("数学建模", "数学竞赛"), List.of("MATLAB", "Python"), List.of("能力锻炼"), 6, false);
        
        log.info("用户数据初始化完成");
    }
    
    private void createDemoStudent(String username, String password, String name, String major,
                                   String discipline, int grade, List<String> interests,
                                   List<String> skills, List<String> goals, int weeklyHours, boolean hasExperience) {
        User student = new User();
        student.setUsername(username);
        student.setPassword(passwordEncoder.encode(password));
        student.setName(name);
        student.setRole(UserRole.STUDENT);
        student.setDepartment(discipline);
        student.setEmail(username + "@example.com");
        userRepository.save(student);
        
        UserProfile profile = new UserProfile();
        profile.setUserId(student.getId());
        profile.setDiscipline(discipline);
        profile.setMajor(major);
        profile.setGrade(grade);
        profile.setInterests(interests);
        profile.setSkills(skills);
        profile.setGoals(goals);
        profile.setWeeklyHours(weeklyHours);
        profile.setHasExperience(hasExperience);
        profile.setPreferredLevel("NATIONAL");
        profile.setDescription("演示账号，用于体验推荐功能");
        profileRepository.save(profile);
    }
    
    private void initCompetitions() {
        try {
            ClassPathResource resource = new ClassPathResource("competitions.json");
            if (!resource.exists()) {
                log.warn("competitions.json 不存在，跳过竞赛库初始化");
                return;
            }
            try (InputStream in = resource.getInputStream()) {
                Map<String, List<Competition>> data = objectMapper.readValue(in, new TypeReference<>() {});
                List<Competition> competitions = data.get("competitions");
                if (competitions != null) {
                    competitionRepository.saveAll(competitions);
                    log.info("竞赛库初始化完成，共 {} 个竞赛", competitions.size());
                }
            }
        } catch (Exception e) {
            log.error("竞赛库初始化失败", e);
        }
    }
    
    private void initExcellentWorks() {
        try {
            ClassPathResource resource = new ClassPathResource("excellent-works.json");
            if (!resource.exists()) {
                log.warn("excellent-works.json 不存在，跳过优秀作品初始化");
                return;
            }
            try (InputStream in = resource.getInputStream()) {
                Map<String, List<ExcellentWork>> data = objectMapper.readValue(in, new TypeReference<>() {});
                List<ExcellentWork> works = data.get("works");
                if (works == null) return;
                // 每次启动全量同步：删除旧数据后按 JSON 重插，保证链接与条目更新即时生效
                excellentWorkRepository.deleteAll();
                final int[] saved = {0};
                for (ExcellentWork w : works) {
                    competitionRepository.findByNameContainingIgnoreCase(w.getCompetitionName()).stream()
                            .findFirst()
                            .ifPresent(c -> {
                                w.setCompetitionId(c.getId());
                                w.setCompetitionName(c.getName());
                                excellentWorkRepository.save(w);
                                saved[0]++;
                            });
                }
                log.info("历年优秀作品同步完成，共 {} 条", saved[0]);
            }
        } catch (Exception e) {
            log.error("历年优秀作品初始化失败", e);
        }
    }
    
    private void initForumAndTeams() {
        User admin = userRepository.findByUsername("admin").orElse(null);
        User student = userRepository.findByUsername("student01").orElse(null);
        if (admin == null || student == null) return;
        
        // 演示团队：student01 为队长
        Team team = new Team();
        team.setName("星辰算法队");
        team.setSlogan("以赛促学，冲进国赛");
        team.setDescription("备战 CCPC 与蓝桥杯，欢迎算法爱好者加入，每周一次集训。");
        team.setLeader(student);
        team.setRecruiting(true);
        team.setSizeLimit(5);
        team.setTargetCompetition("CCPC 中国大学生程序设计竞赛");
        Team savedTeam = teamRepository.save(team);
        
        TeamMember leaderMember = new TeamMember();
        leaderMember.setTeam(savedTeam);
        leaderMember.setUser(student);
        leaderMember.setRole(TeamMember.TeamRole.LEADER);
        teamMemberRepository.save(leaderMember);
        savedTeam.setMemberCount(1);
        teamRepository.save(savedTeam);
        
        // 欢迎帖
        ForumPost p1 = new ForumPost();
        p1.setBoard(ForumPost.ForumBoard.GENERAL);
        p1.setTitle("欢迎来到赛道社区，发帖前请先看这里");
        p1.setContent("这里是竞赛交流社区：\n\n- 找队友：招募队员或毛遂自荐\n- 竞赛问答：赛制、报名、备赛问题\n- 经验分享：获奖复盘与干货\n- 综合交流：聊竞赛、聊学习\n\n祝大家都能找到合适的比赛和靠谱的队友！");
        p1.setAuthor(admin);
        p1.setViewCount(128);
        forumPostRepository.save(p1);
        
        ForumPost p2 = new ForumPost();
        p2.setBoard(ForumPost.ForumBoard.TEAM_FIND);
        p2.setTitle("星辰算法队招募队友，一起冲 CCPC");
        p2.setContent("我们是一支目标明确的算法小队，现招募 2 名队友：\n\n要求：\n1. 熟悉 C++ 或 Python，刷过一定量算法题\n2. 每周能投入 8 小时以上\n3. 大二、大三优先\n\n有意者点击右侧团队卡片申请加入。");
        p2.setAuthor(student);
        p2.setTeam(savedTeam);
        p2.setViewCount(56);
        forumPostRepository.save(p2);
        
        log.info("论坛与演示团队初始化完成");
    }
}
